apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-microservices-ingress
  namespace: demo-microservices
spec:
  ingressClassName: nginx
  rules:
    - host: micro.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
